### ISSUE TITLE
DEVELOPMENT TASKS (MAIN TASK)

### ISSUE THREAD

**Issue by 54UL** [54UL/CC8#6]
## Tasks by order of development

- [ ] IMPLEMENT: REGISTERS MANAGER
- [ ] IMPLEMENT: CPU INTERRUPTS
- [ ] IMPLEMENT: GAME BOY INSTRUCTIONS AND DECODING TABLE
- [ ] IMPLEMENT: GAME BOY OPCODES UNIT TEST
- [x] REFACTOR: RENDERING FUNCTION -> MOVE TO EMULATION LAYER
- [x] REFACTOR: MAIN LOOP -> MOVE TO EMULATION LAYER (EMULATOR LOOP RELATED)
- [x] REFACTOR: INPUT SYSTEM -> MOVE TO EMULATION LAYER
- [x] REFACTOR: FETCH DISPLAY, CLOCK TIMINGS AND OTHER EMULATOR INFO FROM SOME FUNCTION AT THE EMULATION LAYER
- [x] REFACTOR: UI EMULATOR SHELL INTERFACE NEEDS AN REFACTOR TO MEET IMGUI REQUIREMENTS.
- [ ] REFACTOR: MAKE THE OLD UI SHELL SYSTEM LEGACY (THUS TO IMPLEMENT MINIMAL EMULATOR CONTROL ON EMBBED DEVICES)
- [ ] IMPLEMENT/REFACTOR: EMULATOR UI WITH 80CC(own engine) (DESKTOP MODE)  
- [ ] IMPLEMENT: MULTI EMULATOR SELECTOR (AUTOMATIC BASED ON THE PROVIED PROGRAM)
- [ ] SPRITE DEBUGGER AND EXECUTION HEX DUMP ON IMGUI (GAME BOY SPRITES)

## Backlog
- [ ] OPTIMIZATIONS (VERY LAST AFTER GAMEBOY EMULATOR IS RUNNING)
